on:
  push:
    branches:
     - main

jobs:
  loader-client:
    name: Build Projects
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 8
    
    - uses: gradle/actions/setup-gradle@v4

    - name: Make code compatible with old Java
      run: gradle -p tools removeAnnotations

    - name: Run Gradle build
      run: gradle build -x :deob-annotations:build

    - name: Upload Loader-Client Artifact
      uses: actions/upload-artifact@v3
      with:
        name: loader-client
        path: |
          loader/build/libs/*

    - name: Upload Mapview Artifact
      uses: actions/upload-artifact@v3
      with:
        name: mapview
        path: |
          mapview/build/libs/*
