on:
  push:
    branches:
     - main

jobs:
  client:
    name: Build Client
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn package

    - run: mv client/target/client-1.0.jar client/target/rs2-client.jar
    - run: sha256sum client/target/rs2-client.jar | cut -d ' ' -f 1 | tr -d '\n' > client/target/rs2-client.jar.sha256

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: rs2-client
        path: |
          client/target/rs2-client.jar
          client/target/rs2-client.jar.sha256

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: rs2-webclient
        path: webclient/target/js
