on:
  push:
    branches:
     - main

jobs:
  loader-client:
    name: Build Loader and Client
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 8

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Make code compatible with old Java
      run: gradle -p tools removeAnnotations

    - name: Run Gradle build
      run: gradle build -x :deob-annotations:build

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: loader-client
        path: |
          loader/build/libs/*
