on:
  push:
    branches:
     - main

jobs:
  loader-client:
    name: Build Loader and Client
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 8

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Build Client
      run: gradle client:build

    - name: Generate Client SHA Signature
      run: gradle -p tools sig

    - name: Generate Loader
      run: gradle loader:build

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: loader-client
        path: |
          loader/build/libs/*
